minimax/urls.py
from django.contrib import admin
from django.urls import path
from B.views import b1nz, bsjxqd, boms, material, uploads
from Home.views import index, projection, product, bom_interface, guan, three_meeting, notice, output

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index.index),
    path('index', index.index),
    path('test', index.test1),

    path('notice', notice.notice),


    path('projection', projection.projection),
    path('projection_data', projection.get_pro_data),
    path('projection_data/<str:depart>', projection.get_pro_data),
    path('projection_add', projection.projection_add),
    path('projection_edit/<int:id>', projection.projection_edit),
    path('projection_delete/<int:id>', projection.projection_delete),

    path('product', product.product),
    path('product/prosystem/<str:pro_system>', product.product),
    path('product/data', product.get_product_data),
    # path('product/data_all/all', product.get_product_data),
    # path('product/data/<str:condiction_name>', product.get_product_data),
    # path('product/prosystem/data/<str:pro_system>', product.get_product_data),
    path('product_data/<str:condiction>', product.get_product_mat),
    path('product/add/<str:pro_system>', product.product_add),
    path('product/edit/<str:pro_system>/<int:id>', product.product_edit),
    path('product/delete/<str:pro_system>/<int:id>', product.product_delete),

    path('threemeeting', three_meeting.three_meeting),
    path('meeting/add', three_meeting.meeting_add),
    path('meeting/edit/<int:id>', three_meeting.meeting_edit),
    path('meeting/delete/<int:id>', three_meeting.meeting_delete),
    # path('meeting/close/<int:id>', three_meeting.meeting_close),
    path('threemeeting/adddata', three_meeting.get_meeting_data),
    path('threemeeting/onpurchase', three_meeting.three_meeting),
    path('threemeeting/extract/purchase_data', three_meeting.extract_meet_data),
    path('threemeeting/purchase/data', three_meeting.get_purchase_data),
    path('threemeeting/thistime', three_meeting.three_meeting),
    path('threemeeting/not_start', three_meeting.three_meeting),
    path('threemeeting/data/<str:his_this>', three_meeting.get_meeting_product_data),
    
    path('bominterface/ALL1nz', bom_interface.bom_interface),
    path('bominterface/sjXqdall', bom_interface.bom_interface),
    path('bominterface/bom_all', bom_interface.bom_sum),
    path('bominterface/bom_submit', bom_interface.bom_submit),
    path('bominterface/yongyou', bom_interface.bom_interface),
    path('bominterface/batch_compart', bom_interface.bom_interface),
    path('bominterface/material_out', bom_interface.bom_interface),
    path('yy/warehouse', bom_interface.bom_interface),
    path('yy/purchase', bom_interface.bom_interface),
    path('yy/sale_out', bom_interface.bom_interface),
    path('yy/search', bom_interface.search),
    path('bominterface/getData/<str:interface>', bom_interface.get_interface_data),
    
    path('guan', guan.guan),
    path('guan/data', guan.get_guan_data),
    path('guan/add', guan.guan_add),
    path('guan/edit/<str:id>', guan.guan_edit),
    path('guan/delete/<str:id>', guan.guan_delete),

    path('projection_b/<str:pro_no>', material.meterial),

    path('b/1nz/data/<str:pro_no>', b1nz.get_1nz_data),
    path('b/1nz/batch/data/<str:pro_no>', b1nz.get_batch_data),
    path('b/1nz/<str:pro_no>', b1nz.b_1nz),
    path('b/1nz/add/<str:pro_no>', b1nz.b_1nz_add),
    path('b/1nz/edit/<str:pro_no>/<int:id>', b1nz.b_1nz_edit),
    path('b/1nz/delete/<str:pro_no>/<int:id>', b1nz.b_1nz_delete),
    
    path('b/sjxqd/data/<str:pro_no>', bsjxqd.get_sjxqd_data),
    path('b/sjxqd/<str:pro_no>', bsjxqd.b_sjxqd),
    path('b/sjxqd/add/<str:pro_no>', bsjxqd.b_sjxqd_add),
    path('b/sjxqd/edit/<str:pro_no>/<int:id>', bsjxqd.b_sjxqd_edit),
    path('b/sjxqd/delete/<str:pro_no>/<int:id>', bsjxqd.b_sjxqd_delete),
   
    path('b/bom/<str:pro_no>/<str:bsystem>', boms.b_bom),
    path('b/bom/data/<str:pro_no>/<str:bsystem>', boms.get_bom_data),
    path('b/bom/add/<str:pro_no>/<str:bsystem>', boms.b_bom_add),
    path('b/bom/edit/<str:pro_no>/<str:bsystem>/<int:id>', boms.b_bom_edit),
    path('b/bom/delete/<str:pro_no>/<str:bsystem>/<int:id>', boms.b_bom_delete),

    path('upload', uploads.upload),
    path('upload/del/<str:sheet_name>', uploads.upload_del),
    path('upload/data', uploads.get_upload_data),
    path('upload/load/<str:mode>', uploads.load_data),

    path('b/output', output.output),
    path('b/load', output.load_btable),
    # path('edit_inventory_code', output.add_inventory_code),
]

Home/models.py
from datetime import datetime, timedelta

from django.db import models
from B.models import Boms
from bulk_update_or_create import BulkUpdateOrCreateQuerySet


def get_next_week2_date():
    now_date = datetime.now()
    day_num = now_date.isoweekday()
    next_week2 = now_date + timedelta(days=9-day_num)
    return next_week2.strftime("%Y-%m-%d")


class Projection(models.Model):
    objects = BulkUpdateOrCreateQuerySet.as_manager()
    # 项目号
    pro_no = models.CharField(max_length=20, verbose_name='项目号', unique=True)
    # 项目名称
    pro_name = models.CharField(max_length=255, verbose_name='项目名称')
    # 部门编码
    depart_no = models.CharField(max_length=10, verbose_name='部门编码')
    # 客户编码
    client_no = models.CharField(max_length=10, verbose_name='客户编码')
    # 日期
    pro_date = models.DateField(verbose_name='日期')
    # 技术负责人
    pro_tec = models.CharField(max_length=20, verbose_name='技术负责人')
    # 商务负责人
    pro_mer = models.CharField(max_length=40, verbose_name='商务负责人')
    # 客户名称
    client = models.CharField(max_length=40, verbose_name='客户名称')
    # 最终用户
    endUser = models.CharField(max_length=40, verbose_name='最终用户')
    # 项目所在地
    pro_area = models.CharField(max_length=40, verbose_name='项目所在地')
    # SM
    sm = models.CharField(max_length=10, verbose_name='sm')
    # 合同标签
    pro_label = models.CharField(max_length=10, verbose_name='合同标签')
    
    def __str__(self):
        return self.pro_no


class Product(models.Model):
    objects = BulkUpdateOrCreateQuerySet.as_manager()
    # 产品编码
    product_code = models.CharField(verbose_name='产品编码', max_length=30, unique=True)
    # 存货编码
    inventory_code = models.CharField(verbose_name='存货编码', max_length=30, null=True, blank=True)
    # 名称
    product_name = models.CharField(verbose_name='名称', max_length=255, default='', null=True, blank=True)
    # 单位
    unit = models.CharField(verbose_name='单位', max_length=20, default='个', null=True, blank=True)
    # 型号
    product_type = models.CharField(verbose_name="型号", max_length=255, null=True, blank=True)
    # 所属系统
    pro_system = models.SmallIntegerField(verbose_name="所属系统", choices=Boms.m_system_choices, null=True, blank=True)
    # 供应商
    supply = models.CharField(verbose_name='供应商', max_length=100, null=True, blank=True)
    # 供应商编码
    # 供应类型
    # 座位号
    place_no = models.CharField(verbose_name='座位号', max_length=15, null=True, blank=True)
    # 现有库存 
    # inventory_num = models.IntegerField(verbose_name='现有库存', default=0)
    # 备注
    # 详细描述
    detail = models.TextField(verbose_name="详细描述", null=True, blank=True)


class Guan(models.Model):
    objects = BulkUpdateOrCreateQuerySet.as_manager()
    pro_no = models.CharField(verbose_name="批次", max_length=30, null=True, blank=True)
    batch = models.CharField(verbose_name="批次", max_length=30, null=True, blank=True)
    product_num = models.IntegerField(verbose_name="产品数量", null=True, blank=True)
    prod_task_content = models.CharField(verbose_name="生产任务综述", max_length=255, null=True, blank=True)
    product_code = models.CharField(verbose_name="产品编号", max_length=20, null=True, blank=True)
    order_date = models.DateField(verbose_name="邮件下单", null=True, blank=True)
    acc_date = models.DateField(verbose_name="接单日期", null=True, blank=True)
    sj_date = models.DateField(verbose_name="SJ日期", null=True, blank=True)
    expect_date = models.DateField(verbose_name="期望交期", null=True, blank=True)
    table0_update_date = models.DateField(verbose_name="0号表更新日期", null=True, blank=True)
    first_sign_date = models.DateField(verbose_name="首签交期", null=True, blank=True)
    change_date = models.DateField(verbose_name="交期变更", null=True, blank=True)
    responsible = models.CharField(verbose_name="责任人", max_length=20, null=True, blank=True)
    inventory_code = models.CharField(verbose_name="存货编码", max_length=20, null=True, blank=True)
    status = models.CharField(verbose_name="状态", max_length=20, null=True, blank=True)
    warehousing_date = models.DateField(verbose_name="入库日期", null=True, blank=True)
    warehousing_num = models.IntegerField(verbose_name="实际入库数量", null=True, blank=True)
    warehousing_code = models.CharField(verbose_name="入库单号", max_length=20, null=True, blank=True)
    change_record = models.CharField(verbose_name="变更记录", max_length=255, null=True, blank=True)
    attribute = models.CharField(verbose_name="属性", max_length=20, null=True, blank=True)
    description = models.CharField(verbose_name="描述", max_length=255, null=True, blank=True)
    jin1 = models.IntegerField(verbose_name="1#", null=True, blank=True)
    warehousing_status = models.CharField(verbose_name="到货状态", max_length=30, null=True, blank=True)
    assembly_method = models.CharField(verbose_name="组装方式", max_length=20, null=True, blank=True)
    last_deliver_date = models.DateField(verbose_name="最新交期", null=True, blank=True)
    file_place = models.CharField(verbose_name="FB文件夹", max_length=255, null=True, blank=True)
    to_warehouse = models.IntegerField(verbose_name="待入库", null=True, blank=True)
    change_times = models.IntegerField(verbose_name="变更次数", null=True, blank=True)
    under_construction = models.IntegerField(verbose_name="在建", null=True, blank=True)
    success_num = models.IntegerField(verbose_name="产成品", null=True, blank=True)

    need_1nz = models.CharField(verbose_name="1nz需求", max_length=30, null=True, blank=True)
    manage_order_no = models.CharField(verbose_name="管理单号", max_length=20, null=True, blank=True)
    sales_order = models.CharField(verbose_name="销售订单", max_length=20, null=True, blank=True)
    manage_code = models.CharField(verbose_name="管理单号", max_length=50, null=True, blank=True)
    process_code = models.CharField(verbose_name="工艺卡号", max_length=20, null=True, blank=True)

    on_delivery_rate = models.FloatField(verbose_name="准时交付率", null=True, blank=True)
    yield_rate = models.FloatField(verbose_name="良品率", null=True, blank=True)
    man_assembly_time = models.FloatField(verbose_name="机械组装工时", null=True, blank=True)
    el_assembly_time = models.FloatField(verbose_name="电气组装工时", null=True, blank=True)
    quality_check_time = models.FloatField(verbose_name="质检检验工时", null=True, blank=True)
    op_overlap_rate = models.FloatField(verbose_name="工序重叠率", null=True, blank=True)
    
    inventory_num = models.IntegerField(verbose_name="库存", null=True, blank=True)
    warehouse_out_num = models.IntegerField(verbose_name="销售出库", null=True, blank=True)
    assembly_cycle = models.IntegerField(verbose_name="组装周期", null=True, blank=True)
    srd_num = models.IntegerField(verbose_name="SRD数量", null=True, blank=True)


class Bom_sum_record(models.Model):
     objects = BulkUpdateOrCreateQuerySet.as_manager()
     product_code = models.CharField(max_length=20, verbose_name="产品编码")
     inventory_code = models.CharField(max_length=20, verbose_name="存货编码")
     pro_sys_bc = models.JSONField(verbose_name="项目号|系统|bc")
     total_sum = models.IntegerField(verbose_name="总数")
     submit_date = models.DateField(verbose_name="提取时间", default=datetime.now().strftime("%Y-%m-%d"))


class ThreePartMeet(models.Model):
    objects = BulkUpdateOrCreateQuerySet.as_manager()
    threemeet_code = models.CharField(verbose_name="三部会审编码", max_length=20)
    depart = models.CharField(verbose_name="部门", max_length=20)
    pro_no = models.CharField(verbose_name="项目号", max_length=20)
    batch = models.CharField(verbose_name="批次", max_length=50)
    participants = models.CharField(verbose_name="参加人员", max_length=30)
    meet_date = models.DateField(verbose_name="时间", default=get_next_week2_date())
    status_choices = (
        (1, "未开始"),
        (2, "全部通过"),
        (3, "部分通过"),
        (4, "已关闭"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1, blank=True)
    remark = models.CharField(verbose_name="备注", max_length=255, default='', blank=True)
    meet_sign_filepath = models.CharField(verbose_name="签字版文件路径", max_length=255, default='', blank=True)

class threePartRemark(models.Model):
    objects = BulkUpdateOrCreateQuerySet.as_manager()
    three_product_code = models.CharField(verbose_name="流程号", max_length=40)
    threemeet_code = models.CharField(verbose_name="三部会审编码", max_length=20)
    product_code = models.CharField(verbose_name="产品编码", max_length=20)
    pro_no = models.CharField(verbose_name="项目号", max_length=20)
    depart = models.CharField(verbose_name="部门编码", max_length=10)
    batch = models.CharField(verbose_name="批次", max_length=10)
    num = models.IntegerField(verbose_name="数量")
    remark = models.CharField(verbose_name="备注", max_length=255, default="")


# 销售订单
class SaleOrder(models.Model):
    three_product_code = models.CharField(verbose_name="流程号", max_length=40, null=True, blank=True)
    bom = models.CharField(verbose_name="bom", max_length=30, null=True, blank=True)
    business_type = models.CharField(verbose_name="业务类型", max_length=10, null=True, blank=True)
    order_number = models.CharField(verbose_name="订单号", max_length=20, null=True, blank=True)
    prepared_by = models.CharField(verbose_name="制单人", max_length=10, null=True, blank=True)
    order_date = models.DateField(verbose_name="订单日期", null=True, blank=True)
    reviewed_by = models.CharField(verbose_name="审核人", max_length=10, null=True, blank=True)
    audit_date = models.DateField(verbose_name="审核时间", null=True, blank=True)
    close_by = models.CharField(verbose_name="关闭人", max_length=10, null=True, blank=True)
    sale_num = models.IntegerField(verbose_name="数量", null=True, blank=True)
    pre_delevery_date = models.DateField(verbose_name="预计发货日期", null=True, blank=True)
    order_sub_id = models.CharField(verbose_name="订单子表ID", max_length=20, null=True, blank=True)
    unship_num = models.IntegerField(verbose_name="未发货数量", null=True, blank=True)
    un_order = models.IntegerField(verbose_name="未下达采购", null=True, blank=True)
    close_date= models.DateField(verbose_name="关闭日期", null=True, blank=True)

Home/views/guan.py
import re
import pandas as pd 

from django.db.models import Q
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.clickjacking import xframe_options_exempt

from Home.models import Product, Guan
from B.models import Projection, B1nz, Boms
from B.views.boms import del_data
from B.views.b1nz import get_1nz_data
from B.views.bsjxqd import get_sjxqd_data
from B.views.common import choice_map


@xframe_options_exempt
def guan(req):
    return render(req, "guan.html")


def get_guan_data(req):
    page = int(req.GET.get('page'))
    limit = int(req.GET.get('limit'))
    start = (page - 1) * limit
    end = page * limit 
    number = [*range(start, end)]
    data_obj = Guan.objects.all()
    data = [dict(
        no = i + 1,
        pro_no = x.pro_no, 
        batch = x.batch,
        product_num = x.product_num,
        prod_task_content = x.prod_task_content,
        product_code = x.product_code,
        order_date = x.order_date,
        acc_date = x.acc_date,
        sj_date = x.sj_date,
        expect_date = x.expect_date,
        table0_update_date = x.table0_update_date,
        first_sign_date = x.first_sign_date,
        change_date = x.change_date,
        responsible = x.responsible,
        inventory_code = x.inventory_code,
        status = x.status,
        warehousing_date =x.warehousing_date,
        warehousing_num = x.warehousing_num,
        warehousing_code =x.warehousing_code,
        change_record = x.change_record,
        attribute = x.attribute,
        description = x.description,
        jin1 = x.jin1,
        warehousing_status = x.warehousing_status,
        assembly_method = x.assembly_method,
        last_deliver_date = x.last_deliver_date,
        file_place = x.file_place,
        to_warehouse = x.to_warehouse,
        change_times = x.change_times,
        under_construction =x.under_construction,
        success_num = x.success_num,
        need_1nz = x.need_1nz,
        manage_order_no = x.manage_order_no,
        sales_order = x.sales_order,
        manage_code = x.manage_code,
        process_code = x.process_code,
        on_delivery_rate =x.on_delivery_rate,
        yield_rate = x.yield_rate,
        man_assembly_time =  x.man_assembly_time,
        el_assembly_time =x.el_assembly_time,
        quality_check_time = x.quality_check_time,
        op_overlap_rate = x.op_overlap_rate,
        inventory_num = x.inventory_num,
        warehouse_out_num = x.warehouse_out_num,
        assembly_cycle = x.assembly_cycle,
        srd_num = x.srd_num,
    )for i, x in zip(number, data_obj)]

    content = {
        "code": 0,
        "msg": "",
        "count": data_obj.count(),
        "data": data,
    }

    return JsonResponse(content)


def guan_add(req):
    return


def guan_edit(req, id):
    return 

def guan_delete(req, id):
    return

Home/views/notice.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.clickjacking import xframe_options_exempt


@xframe_options_exempt
def notice(req):
    return render(req, "notice.html")

Home/templates/bom_interface.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'imgs/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css' %}">
        <title>Document</title>
    </head>
    <body>
        <div class="layui-card">
            <div class="layui-card-header">
                {% if interface == "bom_all" %}
                    <button class="layui-btn" id="bom_sum">bom汇总</button>
                {% endif %}
                {% if interface == "purchase" or interface == "sale_out" or interface == "warehouse"%}
                <div class="search layui-inline">
                    <div class="layui-input-inline" style="width: 200px;">
                        <input id="yy_search" type="text" name="title" placeholder="产品编码|项目号|存货编码" class="layui-input">
                    </div>
                    <a class="layui-btn" id="yy_search_btn">筛选</a>
                </div>
                {% endif %}
                <!-- {% if interface == "purchase" %}
                    <button class="layui-btn" id="Q9_0">Q9原始</button>
                    <button class="layui-btn" id="Q9">Q9</button>
                    <button class="layui-btn" id="Q4">Q4</button>
                    {% endif %}
                {% if interface == "sale_out" %}    
                    <button class="layui-btn" id="Q5">Q5</button>
                {% endif %}
                {% if interface == "warehouse" %}    
                    <button class="layui-btn" id="Q7">Q7</button>
                {% endif %} -->
            </div>
            <div class="layui-card-body">
                <table class="layui-hide" id="demo" lay-filter="test"></table>
            </div>
        </div>
        <script type="text/html" id="barDemo">
            <a class="layui-btn layui-btn-normal layui-btn-xs" id="product_edit" lay-event="edit">编辑</a>
            <a class="layui-btn layui-btn-danger layui-btn-xs" id="product_delete" lay-event="delete">删除</a>
        </script>
        <script src="{% static 'plugins/layui/layui.js' %}"></script>
        <script src="{% static 'js/interface.js' %}" type="module"></script>

    </body>
    
</html>

Home/templates/meeting_add.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css' %}">
        <title>Document</title>
    </head>
    <body>
        <div class="layui-card">
            <div class="layui-card-header"></div>
            <div class="layui-card-body">
                <div id="meeting_add"  data-date="{{date}}">
                    <form novalidate class="layui-form" action="{{action}}" method="post">
                        {% csrf_token %}
                        {% for item in form %}
                        <div class="layui-form-item">
                            <label class="layui-form-label">{{ item.label }}</label>
                            <div class="layui-input-block">
                                {{item}}
                                <span style="color: red;">{{ item.errors.0 }}</span>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- 添加 -->
        

        <script src="{% static 'plugins/layui/layui.js' %} "></script>
        <script>
            var laydate = layui.laydate; //日期
            var $ = layui.$;
            laydate.render({
                elem: '#id_meet_date',
                value: $("#meeting_add").attr("data-date"),
                min: $("#meeting_add").attr("data-date"),
            });

            // 设置threemeet_code的默认值
            // $("#id_threemeet_code").val($("#meeting_add").attr("data-threecode"));
            // 'status', 'remark'
            // $("#id_meet_sign_filepath").attr("disabled", true);
            // $("#id_status").attr("disabled", true);
            // $("#id_remark").attr("disabled", true);

            

    </script>
    </body>
</html>

Home/templates/product_add.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css' %}">
        <title>product add</title>
    </head>
    <body>
        <div id="product_add">
            {% comment %} <button class="layui-btn layui-btn-primary pro_system">{{pro_system}}</button> {% endcomment %}
            <form class="layui-form pro_system" action="/product/add/{{pro_system}}" id="{{pro_system}}" method="post" product_code="{{product_code}}">
                {% csrf_token %}
                {% for item in form %}
                <div class="layui-form-item">
                    <label class="layui-form-label">{{ item.label }}</label>
                    <div class="layui-input-block">
                        {{item}}
                        <span style="color: red;">{{ item.errors.0 }}</span>
                    </div>
                </div>
                {% endfor %}
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
        </div>

        <script src="{% static 'plugins/layui/layui.js' %} "></script>
        <script>
            var $ = layui.$;
            // 生成产品编码
            $("#id_product_code").val($(".pro_system").attr("product_code"));
            // 默认选中所属系统
            var pro_system = $(".pro_system").attr('id'); 
            $("select").find("option:contains("+pro_system+")").attr("selected",true); 
        </script>
        
    </body>
</html>

Home/templates/product_edit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css'%}">
        <title>Document</title>
    </head>
    <body>
        <!-- 添加项目 -->
        <div id="projection_add">
            <form novalidate class="layui-form" action="/product/edit/{{pro_system}}/{{id}}"method="post">
                {% csrf_token %}
                {% for item in form %}
                <div class="layui-form-item">
                    <label class="layui-form-label">{{ item.label }}</label>
                    <div class="layui-input-block">
                        {{item}}
                        <span style="color: red;">{{ item.errors.0 }}</span>
                    </div>
                </div>
                {% endfor %}
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
        </div>

        <script src="{% static 'plugins/layui/layui.js' %}"></script>
        <script>
            var laydate = layui.laydate; //日期
            laydate.render({
                elem: '#id_pro_date'
            });
    </script>
    </body>
</html>

Home/templates/projection_add.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css' %}">
        <title>Document</title>
    </head>
    <body>
        <!-- 添加项目 -->
        <div id="projection_add">
            <form novalidate class="layui-form" action="/projection_add" method="post">
                {% csrf_token %}
                {% for item in form %}
                <div class="layui-form-item">
                    <label class="layui-form-label">{{ item.label }}</label>
                    <div class="layui-input-block">
                        {{item}}
                        <span style="color: red;">{{ item.errors.0 }}</span>
                    </div>
                </div>
                {% endfor %}
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit
                            lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn
                            layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
        </div>

        <script src="{% static 'plugins/layui/layui.js' %} "></script>
        <script>
            var laydate = layui.laydate; //日期
            laydate.render({
                elem: '#id_pro_date'
            });
    </script>
    </body>
</html>

Home/templates/test.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'imgs/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'plugins/layui/css/layui.css' %}">
        <style>
            
        </style>
        <title>Document</title>
    </head>
    <body>
        
        
               
        
        <script type="text/html" id="barDemo">
            <a class="layui-btn layui-btn layui-btn-xs" id="projection_b"  lay-event="btable" href="javascript:;">b表</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs" id="projection_edit" lay-event="edit">编辑</a>
            <a class="layui-btn layui-btn-danger layui-btn-xs" id="projection_delete" lay-event="delete">删除</a>
        </script>
        <script src="{% static 'plugins/layui/layui.js' %}"></script>
        <script>
            var table = layui.table;
            var $ = layui.$;
            
        </script>

    </body>
</html>